var MONSTERS = {
  // FIRE --- MED LIFE MED ATTACK LOW DEFENCE
  "zimbo": {
    "name": "zimbo",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 76,
    "attack": 87,
    "defence": 19,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "waaq": {
    "name": "waaq",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 56,
    "attack": 94,
    "defence": 7,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "ugo": { // woods day
    "name": "ugo",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 75,
    "attack": 42,
    "defence": 11,
    "drops": [
      32,
      22,
      21,
      42,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "trii": { // river day
    "name": "trii",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 65,
    "attack": 72,
    "defence": 6,
    "drops": [
      31,
      32,
      45,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "raa": {
    "name": "raa",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 34,
    "attack": 42,
    "defence": 23,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "quna": {
    "name": "quna",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 46,
    "attack": 124,
    "defence": 9,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "liku": { // forest day
    "name": "liku",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 134,
    "attack": 34,
    "defence": 6,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "hilo": {
    "name": "hilo",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 46,
    "attack": 214,
    "defence": 13,
    "drops": [
      21,
      32,
      52,
      23,
      41,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "gut": {
    "name": "gut",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 134,
    "attack": 76,
    "defence": 24,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "gira": { // castle day
    "name": "gira",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 146,
    "attack": 56,
    "defence": 4,
    "drops": [
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "gilo": {
    "name": "gilo",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 124,
    "attack": 37,
    "defence": 38,
    "drops": [
      143,
      16,
      152,
      12,
      138,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "dosuk": {
    "name": "dosuk",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 96,
    "attack": 34,
    "defence": 31,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "devy": {
    "name": "devy",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 112,
    "attack": 46,
    "defence": 14,
    "drops": [
      123,
      324,
      134,
      421,
      125,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "burnnu": {
    "name": "burnnu",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 96,
    "attack": 31,
    "defence": 8,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "bak": {
    "name": "bak",
    "type": "fire",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 103,
    "attack": 26,
    "defence": 17,
    "drops": [
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  // WATER --- HIGH LIFE MED ATTACK MED DEFENCE
  "yittu": {
    "name": "yittu",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 213,
    "attack": 39,
    "defence": 25,
    "drops": [
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "uroga": {
    "name": "uroga",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 188,
    "attack": 34,
    "defence": 14,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "tri": { // woods night
    "name": "tri",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 147,
    "attack": 36,
    "defence": 17,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "terry": {
    "name": "terry",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 133,
    "attack": 21,
    "defence": 23,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "suku": { // river night
    "name": "suku",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 126,
    "attack": 41,
    "defence": 24,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "showy": {
    "name": "showy",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 143,
    "attack": 15,
    "defence": 24,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "samy": {
    "name": "samy",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 134,
    "attack": 31,
    "defence": 31,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "safa": { // forest night
    "name": "safa",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 178,
    "attack": 27,
    "defence": 18,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "raer": {
    "name": "raer",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 182,
    "attack": 32,
    "defence": 37,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "quatta": {
    "name": "quatta",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 178,
    "attack": 24,
    "defence": 37,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "oxo": {
    "name": "oxo",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 198,
    "attack": 42,
    "defence": 45,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "leka": { // castle night
    "name": "leka",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 213,
    "attack": 36,
    "defence": 41,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "leef": {
    "name": "leef",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 173,
    "attack": 21,
    "defence": 23,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "lazo": {
    "name": "lazo",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 321,
    "attack": 21,
    "defence": 24,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "krus": { // beach day
    "name": "krus",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 114,
    "attack": 41,
    "defence": 27,
    "drops": [
      124,
      52,
      36,
      122,
      124,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "krub": {
    "name": "krub",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 176,
    "attack": 32,
    "defence": 41,
    "drops": [
      54,
      23,
      35,
      12,
      42,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "jatu": {
    "name": "jatu",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 194,
    "attack": 29,
    "defence": 41,
    "drops": [
      124,
      54,
      211,
      153,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "goot": {
    "name": "goot",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 234,
    "attack": 34,
    "defence": 35,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "foreza": {
    "name": "foreza",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 294,
    "attack": 31,
    "defence": 27,
    "drops": [
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "fatu": {
    "name": "fatu",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 324,
    "attack": 24,
    "defence": 36,
    "drops": [
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "farro": {
    "name": "farro",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 230,
    "attack": 32,
    "defence": 43,
    "drops": [
      34,
      21,
      35,
      23,
      56,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "devu": {
    "name": "devu",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 294,
    "attack": 64,
    "defence": 12,
    "drops": [
      111,
      142,
      152,
      124,
      123,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "ben": {
    "name": "ben",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 298,
    "attack": 32,
    "defence": 6,
    "drops": [
      43,
      21,
      34,
      56,
      12,
      32,
      2,
      53,
      12,
      "capture"
    ]
  },
  "bekkut": {
    "name": "bekkut",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 344,
    "attack": 39,
    "defence": 32,
    "drops": [
      13,
      11,
      14,
      16,
      11,
      11,
      11,
      112,
      "capture",
      "capture"
    ]
  },
  "beca": { // beach night
    "name": "beca",
    "type": "water",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 400,
    "attack": 23,
    "defence": 37,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  // EARTH --- HIGH LIFE LOW ATTACK MED DEFENCE
  "zulo": {
    "name": "zulo",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 144,
    "attack": 34,
    "defence": 29,
    "drops": [
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "zilla": {
    "name": "zilla",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 157,
    "attack": 38,
    "defence": 54,
    "drops": [
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "ziite": { // beach night
    "name": "ziite",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 134,
    "attack": 14,
    "defence": 47,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "ziit": {
    "name": "ziit",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 131,
    "attack": 26,
    "defence": 21,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "zeet": {
    "name": "zeet",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 133,
    "attack": 24,
    "defence": 45,
    "drops": [
      12,
      14,
      13,
      16,
      17,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "zam": {
    "name": "zam",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 173,
    "attack": 32,
    "defence": 37,
    "drops": [
      124,
      152,
      142,
      153,
      134,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "yole": { // beach day
    "name": "yole",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 169,
    "attack": 21,
    "defence": 46,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "triano": { // woods night
    "name": "triano",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 197,
    "attack": 24,
    "defence": 33,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "torro": {
    "name": "torro",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 213,
    "attack": 19,
    "defence": 32,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "siny": { // woods days
    "name": "siny",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 134,
    "attack": 42,
    "defence": 34,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "sefa": { // river night
    "name": "sefa",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 156,
    "attack": 13,
    "defence": 56,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture",
      "capture",
      "capture"
    ]
  },
  "rosy": {
    "name": "rosy",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 137,
    "attack": 17,
    "defence": 32,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "quien": {
    "name": "quien",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 156,
    "attack": 14,
    "defence": 35,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "purro": {
    "name": "purro",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 174,
    "attack": 36,
    "defence": 47,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "patu": {
    "name": "patu",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 156,
    "attack": 42,
    "defence": 53,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "meza": { // river day forest night
    "name": "meza",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 142,
    "attack": 21,
    "defence": 42,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "mate": {
    "name": "mate",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 146,
    "attack": 21,
    "defence": 54,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "lili": { // forest day
    "name": "lili",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 146,
    "attack": 26,
    "defence": 47,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "jorry": {
    "name": "jorry",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 123,
    "attack": 18,
    "defence": 54,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "garu": { // castle night
    "name": "garu",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 214,
    "attack": 23,
    "defence": 35,
    "drops": [
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "gaa": { // castle day
    "name": "gaa",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 316,
    "attack": 23,
    "defence": 57,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "fedric": {
    "name": "fedric",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 415,
    "attack": 19,
    "defence": 67,
    "drops": [
      "health potion",
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture",
      "capture",
      "capture"
    ]
  },
  "feat": {
    "name": "feat",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 213,
    "attack": 23,
    "defence": 49,
    "drops": [
      12,
      14,
      11,
      15,
      16,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "deve": {
    "name": "deve",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 164,
    "attack": 31,
    "defence": 69,
    "drops": [
      124,
      142,
      123,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "cacus": {
    "name": "cacus",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 242,
    "attack": 23,
    "defence": 87,
    "drops": [
      "health potion",
      32,
      12,
      42,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "brotto": {
    "name": "brotto",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 113,
    "attack": 36,
    "defence": 76,
    "drops": [
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "bronno": {
    "name": "bronno",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 213,
    "attack": 27,
    "defence": 67,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "brere": {
    "name": "brere",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 285,
    "attack": 31,
    "defence": 76,
    "drops": [
      12,
      34,
      11,
      5,
      24,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "boto": {
    "name": "boto",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 210,
    "attack": 12,
    "defence": 45,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "boon": {
    "name": "boon",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 234,
    "attack": 15,
    "defence": 54,
    "drops": [
      47,
      31,
      43,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "bettun": {
    "name": "bettun",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 170,
    "attack": 27,
    "defence": 39,
    "drops": [
      150,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "belu": {
    "name": "belu",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 240,
    "attack": 23,
    "defence": 33,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "batu": {
    "name": "batu",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 360,
    "attack": 13,
    "defence": 26,
    "drops": [
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "banno": {
    "name": "banno",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 177,
    "attack": 21,
    "defence": 31,
    "drops": [
      67,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "bannu": {
    "name": "bannu",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": "210",
    "attack": 11,
    "defence": 36,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "baart": {
    "name": "baart",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 140,
    "attack": 13,
    "defence": 36,
    "drops": [
      14,
      12,
      16,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "baa": {
    "name": "baa",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 112,
    "attack": 16,
    "defence": 46,
    "drops": [
      13,
      19,
      17,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "bakket": {
    "name": "bakket",
    "type": "earth",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 42,
    "attack": 27,
    "defence": 76,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  // WIND --- LOW LIFE HIGH ATTACK LOW DEFENCE
  "zomo": { // woods night
    "name": "zomo",
    "type": "wind",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 67,
    "attack": 89,
    "defence": 14,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "yaka": { // woods day river night forest day
    "name": "yaka",
    "type": "wind",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 75,
    "attack": 84,
    "defence": 11,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "staa": { // river day beach day forest night
    "name": "staa",
    "type": "wind",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 102,
    "attack": 56,
    "defence": 14,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "site": { // beach night castle day
    "name": "site",
    "type": "wind",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 94,
    "attack": 67,
    "defence": 24,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "sig": {
    "name": "sig",
    "type": "wind",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 87,
    "attack": 56,
    "defence": 15,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "bun": { // castle night city day
    "name": "bun",
    "type": "wind",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 114,
    "attack": 47,
    "defence": 0,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "binny": {
    "name": "binny",
    "type": "wind",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 76,
    "attack": 37,
    "defence": 21,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "beak": { // city night
    "name": "beak",
    "type": "wind",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 89,
    "attack": 47,
    "defence": 14,
    "drops": [
      57,
      34,
      82,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  // DARK --- LOW LIFE HIGH ATTACK LOW DEFENCE
  "zilo": {
    "name": "zilo",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 93,
    "attack": 145,
    "defence": 5,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "zambo": {
    "name": "zambo",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 56,
    "attack": 106,
    "defence": 4,
    "drops": [
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "tommera": {
    "name": "tommera",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 42,
    "attack": 64,
    "defence": 4,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "spidda": { // woods night
    "name": "spidda",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 36,
    "attack": 78,
    "defence": 3,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "sarrow": {
    "name": "sarrow",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 134,
    "attack": 86,
    "defence": 14,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "saaa": { // river night
    "name": "saaa",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 47,
    "attack": 126,
    "defence": 14,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "ratu": {
    "name": "ratu",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 45,
    "attack": 98,
    "defence": 32,
    "drops": [
      24,
      42,
      23,
      124,
      12,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "qita": {
    "name": "qita",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 15,
    "attack": 154,
    "defence": 3,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "potu": { // beach night
    "name": "potu",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 74,
    "attack": 78,
    "defence": 5,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "mossu": {
    "name": "mossu",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 84,
    "attack": 97,
    "defence": 4,
    "drops": [
      524,
      524,
      642,
      245,
      532,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "machu": {
    "name": "machu",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 76,
    "attack": 114,
    "defence": 3,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "leaf": { // forest night
    "name": "leaf",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 64,
    "attack": 61,
    "defence": 4,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "lando": {
    "name": "lando",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 31,
    "attack": 86,
    "defence": 21,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "koto": {
    "name": "koto",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 75,
    "attack": 95,
    "defence": 43,
    "drops": [
      123,
      321,
      211,
      126,
      145,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "jojo": {
    "name": "jojo",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 34,
    "attack": 167,
    "defence": 3,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "jet": {
    "name": "jet",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 153,
    "attack": 45,
    "defence": 41,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "jelly": {
    "name": "jelly",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 45,
    "attack": 78,
    "defence": 34,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "grim": {
    "name": "grim",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 666,
    "attack": 124,
    "defence": 0,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "frea": { // castle night
    "name": "frea",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 128,
    "attack": 56,
    "defence": 16,
    "drops": [
      123,
      41,
      54,
      76,
      62,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "fea": {
    "name": "fea",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 79,
    "attack": 121,
    "defence": 3,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "devl": {
    "name": "devl",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 89,
    "attack": 134,
    "defence": 6,
    "drops": [
      321,
      134,
      241,
      142,
      512,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "carro": {
    "name": "carro",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 12,
    "attack": 1000,
    "defence": 0,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "buu": {
    "name": "buu",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 134,
    "attack": 89,
    "defence": 0,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "boo": {
    "name": "boo",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 107,
    "attack": 120,
    "defence": 6,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "belly": {
    "name": "belly",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 111,
    "attack": 76,
    "defence": 8,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "batty": {
    "name": "batty",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 97,
    "attack": 86,
    "defence": 16,
    "drops": [
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "barra": {
    "name": "barra",
    "type": "dark",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 111,
    "attack": 79,
    "defence": 11,
    "drops": [
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  // LIGHT --- HIGH LIFE LOW ATTACK HIGH DEFENCE
  "tora": {
    "name": "tora",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 213,
    "attack": 16,
    "defence": 21,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "toat": {
    "name": "toat",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 414,
    "attack": 8,
    "defence": 93,
    "drops": [
      13,
      32,
      52,
      12,
      56,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "tiin": {
    "name": "tiin",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 194,
    "attack": 36,
    "defence": 74,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "teqa": { // woods day
    "name": "teqa",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 213,
    "attack": 32,
    "defence": 87,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "uni": { // river day
    "name": "uni",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 541,
    "attack": 97,
    "defence": 45,
    "drops": [
      341,
      42,
      133,
      44,
      12,
      141,
      null,
      null,
      null,
      "capture"
    ]
  },
  "tebua": { // beach day
    "name": "tebua",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 243,
    "attack": 13,
    "defence": 76,
    "drops": [
      123,
      143,
      125,
      153,
      132,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "tarrot": {
    "name": "tarrot",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 213,
    "attack": 24,
    "defence": 54,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "tarret": {
    "name": "tarret",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 232,
    "attack": 16,
    "defence": 67,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "skut": {
    "name": "skut",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 145,
    "attack": 45,
    "defence": 76,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "sera": {
    "name": "sera",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 214,
    "attack": 15,
    "defence": 56,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "sat": {
    "name": "sat",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 243,
    "attack": 24,
    "defence": 66,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "sannu": {
    "name": "sannu",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 168,
    "attack": 32,
    "defence": 45,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture",
      "capture",
      "capture"
    ]
  },
  "sammy": { // forest day
    "name": "sammy",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 267,
    "attack": 17,
    "defence": 49,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "sam": {
    "name": "sam",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 314,
    "attack": 14,
    "defence": 56,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "rea": {
    "name": "rea",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 243,
    "attack": 23,
    "defence": 67,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "phato": {
    "name": "phato",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 196,
    "attack": 9,
    "defence": 56,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "mach": { // castle day
    "name": "mach",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 174,
    "attack": 14,
    "defence": 91,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "maby": {
    "name": "maby",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 245,
    "attack": 21,
    "defence": 49,
    "drops": [
      214,
      123,
      205,
      152,
      164,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "lulu": {
    "name": "lulu",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 217,
    "attack": 24,
    "defence": 54,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "liet": {
    "name": "liet",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 214,
    "attack": 13,
    "defence": 76,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "lerra": {
    "name": "lerra",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 411,
    "attack": 56,
    "defence": 13,
    "drops": [
      57,
      35,
      52,
      74,
      64,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "janu": {
    "name": "janu",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 455,
    "attack": 23,
    "defence": 67,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "hunny": {
    "name": "hunny",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 654,
    "attack": 37,
    "defence": 87,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "golo": {
    "name": "golo",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 456,
    "attack": 34,
    "defence": 94,
    "drops": [
      251,
      312,
      241,
      null,
      null,
      null,
      null,
      "capture",
      "capture",
      "capture"
    ]
  },
  "goldy": {
    "name": "goldy",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 546,
    "attack": 16,
    "defence": 45,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "golden": {
    "name": "golden",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 675,
    "attack": 87,
    "defence": 87,
    "drops": [
      324,
      531,
      321,
      524,
      316,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "ginny": {
    "name": "ginny",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 256,
    "attack": 210,
    "defence": 92,
    "drops": [
      134,
      142,
      125,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "gaaet": {
    "name": "gaaet",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 674,
    "attack": 24,
    "defence": 68,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "diato": {
    "name": "diato",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 2000,
    "attack": 2,
    "defence": 84,
    "drops": [
      544,
      544,
      544,
      544,
      544,
      544,
      544,
      544,
      544,
      "capture"
    ]
  },
  "bunnu": {
    "name": "bunnu",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 432,
    "attack": 21,
    "defence": 64,
    "drops": [
      "health potion",
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "borro": {
    "name": "borro",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 343,
    "attack": 19,
    "defence": 99,
    "drops": [
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "bessy": {
    "name": "bessy",
    "type": "light",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 500,
    "attack": 17,
    "defence": 89,
    "drops": [
      "health potion",
      "health potion",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  // MEME --- OVERALL OP
  "welp": {
    "name": "welp",
    "type": "meme",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 541,
    "attack": 111,
    "defence": 69,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "syd barrel": {
    "name": "syd barrel",
    "type": "meme",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 314,
    "attack": 134,
    "defence": 86,
    "drops": [
      "capture",
      "capture",
      "capture",
      "capture",
      "capture",
      "capture",
      "capture",
      "capture",
      "capture",
      "capture"
    ]
  },
  "sorrow": {
    "name": "sorrow",
    "type": "meme",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 2100,
    "attack": 23,
    "defence": 54,
    "drops": [
      543,
      543,
      543,
      543,
      543,
      543,
      543,
      543,
      543,
      "capture"
    ]
  },
  "so": {
    "name": "so",
    "type": "meme",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 234,
    "attack": 154,
    "defence": 76,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "sith": {
    "name": "sith",
    "type": "meme",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 256,
    "attack": 452,
    "defence": 36,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "seriosity": {
    "name": "seriosity",
    "type": "meme",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 354,
    "attack": 145,
    "defence": 87,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture",
      "capture"
    ]
  },
  "pase": {
    "name": "pase",
    "type": "meme",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 257,
    "attack": 164,
    "defence": 76,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "lolo": {
    "name": "lolo",
    "type": "meme",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 234,
    "attack": 214,
    "defence": 87,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "johncena": {
    "name": "johncena",
    "type": "meme",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 10000,
    "attack": 10000,
    "defence": 100,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  },
  "angy": {
    "name": "angy",
    "type": "meme",
    "level": 0,
    "xp": 0,
    "ult": 0,
    "life": 240,
    "attack": 46,
    "defence": 76,
    "drops": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "capture"
    ]
  }
};
